### PR TITLE
Test 1.11

### PR DESCRIPTION
**Pull request by svchb**
Not to be merged.

Just to give an idea if 1.11 will cause any issues.

### CODE REVIEW

**Comment by svchb** [comment]
WIth beta1:
- fails oscillating_drop_2d.jl
- and the related validation case

**Comment by svchb** [comment]
Beta-2:
- dam_break validation fails
- oscillating drop diverges

There is a performance regression in beta1 and 2 which also effects us which causes about 30% slower execution.

**Comment by svchb** [comment]
RC-1:
All Tests                                                           |  145     3    148  37m05.0s
  Examples                                                          |  124     1    125  28m54.4s
    Fluid                                                           |   97     1     98  20m08.0s
      fluid/oscillating_drop_2d.jl                                  |    3     1      4     53.6s
      fluid/hydrostatic_water_column_2d.jl                          |    3            3     19.2s
      fluid/hydrostatic_water_column_2d.jl with source term damping |    3            3     15.2s
      fluid/hydrostatic_water_column_2d.jl with SummationDensity    |    3            3     19.0s
      fluid/hydrostatic_water_column_3d.jl                          |    3            3     27.1s
      fluid/hydrostatic_water_column_3d.jl with SummationDensity    |    3            3     32.8s
      fluid/hydrostatic_water_column_edac_2d.jl                     |    3            3     16.3s
      fluid/accelerated_tank_2d.jl                                  |    3            3     15.8s
      fluid/dam_break_2d.jl                                         |    3            3     32.1s
      fluid/dam_break_2d.jl with KernelAbstractions.jl              |    3            3     25.3s
      fluid/dam_break_3d.jl                                         |    3            3     21.1s
      fluid/falling_water_column_2d.jl                              |    3            3     13.5s
      fluid/periodic_channel_2d.jl                                  |    3            3     21.4s
      fluid/pipe_flow_2d.jl                                         |    3            3     53.6s
      fluid/dam_break_2d_surface_tension.jl                         |    3            3   1m23.9s
      fluid/sphere_surface_tension_2d.jl                            |    3            3     10.6s
      fluid/sphere_surface_tension_3d.jl                            |    3            3     49.6s
      fluid/falling_water_spheres_2d.jl                             |    3            3   1m15.9s
      fluid/falling_water_spheres_3d.jl                             |    3            3   1m53.3s
      fluid/sphere_surface_tension_wall_2d.jl                       |    1            1   2m32.0s
      fluid/moving_wall_2d.jl                                       |    3            3     15.4s
      dam_break_2d.jl with corrections                              |   36           36   5m40.0s
        continuity_reinit                                           |    3            3     16.1s
        gradient_continuity_correction                              |    3            3     31.6s
        gradient_summation_correction                               |    3            3     32.9s
        no_correction                                               |    3            3     17.8s
        shepard_kernel_correction                                   |    3            3     24.0s
        blended_gradient_continuity_correction                      |    3            3     30.4s
        mixed_kernel_gradient_summation_correction                  |    3            3     42.7s
        akinci_free_surf_correction                                 |    3            3     17.9s
        kernel_correction_summation_correction                      |    3            3     29.4s
        mixed_kernel_gradient_continuity_correction                 |    3            3     38.4s
        kernel_correction_continuity_correction                     |    3            3     26.4s
        blended_gradient_summation_correction                       |    3            3     31.6s
    Solid                                                           |    3            3     21.2s
      solid/oscillating_beam_2d.jl                                  |    3            3     21.2s
    FSI                                                             |   12           12   7m11.6s
      fsi/falling_water_column_2d.jl                                |    3            3     28.5s
      fsi/dam_break_plate_2d.jl                                     |    3            3     59.8s
      fsi/dam_break_gate_2d.jl                                      |    3            3   3m58.2s
      fsi/falling_spheres_2d.jl                                     |    3            3   1m44.9s
    N-Body                                                          |    6            6     27.5s
      n_body/n_body_solar_system.jl                                 |    3            3      5.8s
      n_body/n_body_benchmark_trixi.jl                              |    1            1     13.9s
      n_body/n_body_benchmark_reference.jl                          |    1            1      3.9s
      n_body/n_body_benchmark_reference_faster.jl                   |    1            1      3.8s
    Postprocessing                                                  |    6            6     46.1s
      postprocessing/interpolation_plane.jl                         |    2            2     29.3s
      postprocessing/interpolation_point_line.jl                    |    2            2      2.6s
      postprocessing/postprocessing.jl                              |    2            2     14.0s
  DEM                                                               |    3            3     10.7s
    dem/rectangular_tank_2d.jl                                      |    3            3     10.6s
  Validation                                                        |   18     2     20   7m59.8s
    general                                                         |    4            4     57.6s
    oscillating_beam_2d                                             |    7            7   1m46.6s
    dam_break_2d                                                    |    7     2      9   5m15.4s

**Comment by svchb** [comment]
1.10:
All Tests                                                           |  148    148  29m17.2s
  Examples                                                          |  125    125  23m13.8s
    Fluid                                                           |   98     98  16m41.1s
      fluid/oscillating_drop_2d.jl                                  |    4      4   1m14.1s
      fluid/hydrostatic_water_column_2d.jl                          |    3      3     15.6s
      fluid/hydrostatic_water_column_2d.jl with source term damping |    3      3     12.7s
      fluid/hydrostatic_water_column_2d.jl with SummationDensity    |    3      3     15.3s
      fluid/hydrostatic_water_column_3d.jl                          |    3      3     22.3s
      fluid/hydrostatic_water_column_3d.jl with SummationDensity    |    3      3     27.1s
      fluid/hydrostatic_water_column_edac_2d.jl                     |    3      3     13.0s
      fluid/accelerated_tank_2d.jl                                  |    3      3     13.1s
      fluid/dam_break_2d.jl                                         |    3      3     23.7s
      fluid/dam_break_2d.jl with KernelAbstractions.jl              |    3      3     18.4s
      fluid/dam_break_3d.jl                                         |    3      3     17.2s
      fluid/falling_water_column_2d.jl                              |    3      3     11.0s
      fluid/periodic_channel_2d.jl                                  |    3      3     18.5s
      fluid/pipe_flow_2d.jl                                         |    3      3     52.7s
      fluid/dam_break_2d_surface_tension.jl                         |    3      3   1m11.3s
      fluid/sphere_surface_tension_2d.jl                            |    3      3      7.6s
      fluid/sphere_surface_tension_3d.jl                            |    3      3     43.4s
      fluid/falling_water_spheres_2d.jl                             |    3      3   1m01.6s
      fluid/falling_water_spheres_3d.jl                             |    3      3   1m32.7s
      fluid/sphere_surface_tension_wall_2d.jl                       |    1      1   2m12.1s
      fluid/moving_wall_2d.jl                                       |    3      3     12.5s
      dam_break_2d.jl with corrections                              |   36     36   4m04.0s
        continuity_reinit                                           |    3      3     13.2s
        gradient_continuity_correction                              |    3      3     20.4s
        gradient_summation_correction                               |    3      3     22.0s
        no_correction                                               |    3      3     13.8s
        shepard_kernel_correction                                   |    3      3     18.7s
        blended_gradient_continuity_correction                      |    3      3     20.1s
        mixed_kernel_gradient_summation_correction                  |    3      3     29.6s
        akinci_free_surf_correction                                 |    3      3     14.6s
        kernel_correction_summation_correction                      |    3      3     21.0s
        mixed_kernel_gradient_continuity_correction                 |    3      3     28.9s
        kernel_correction_continuity_correction                     |    3      3     19.3s
        blended_gradient_summation_correction                       |    3      3     21.7s
    Solid                                                           |    3      3     12.7s
      solid/oscillating_beam_2d.jl                                  |    3      3     12.7s
    FSI                                                             |   12     12   5m17.4s
      fsi/falling_water_column_2d.jl                                |    3      3     19.4s
      fsi/dam_break_plate_2d.jl                                     |    3      3     47.9s
      fsi/dam_break_gate_2d.jl                                      |    3      3   2m44.3s
      fsi/falling_spheres_2d.jl                                     |    3      3   1m25.6s
    N-Body                                                          |    6      6     26.7s
      n_body/n_body_solar_system.jl                                 |    3      3      4.6s
      n_body/n_body_benchmark_trixi.jl                              |    1      1     15.0s
      n_body/n_body_benchmark_reference.jl                          |    1      1      3.3s
      n_body/n_body_benchmark_reference_faster.jl                   |    1      1      3.7s
    Postprocessing                                                  |    6      6     35.9s
      postprocessing/interpolation_plane.jl                         |    2      2     23.4s
      postprocessing/interpolation_point_line.jl                    |    2      2      2.1s
      postprocessing/postprocessing.jl                              |    2      2     10.2s
  DEM                                                               |    3      3      8.9s
    dem/rectangular_tank_2d.jl                                      |    3      3      8.9s
  Validation                                                        |   20     20   5m54.4s
    general                                                         |    4      4     44.1s
    oscillating_beam_2d                                             |    7      7   1m03.1s
    dam_break_2d                                                    |    9      9   4m07.0s

**Comment by svchb** [comment]
| Test Name                                                       | RC 1 (s) | 1.10 (s) | Percentage Difference (%) |
|-----------------------------------------------------------------|-----------------|-----------------|---------------------------|
| All Tests                                                       | 2225            | 1757.2          | -21.02                    |
| Examples                                                        | 1734.4          | 1393.8          | -19.64                    |
| Fluid                                                           | 1208            | 1001.1          | -17.11                    |
| fluid/oscillating_drop_2d.jl                                    | 53.6            | 74.1            | 38.25                     |
| fluid/hydrostatic_water_column_2d.jl                            | 19.2            | 15.6            | -18.75                    |
| fluid/hydrostatic_water_column_2d.jl with source term damping   | 15.2            | 12.7            | -16.45                    |
| fluid/hydrostatic_water_column_2d.jl with SummationDensity      | 19.0            | 15.3            | -19.47                    |
| fluid/hydrostatic_water_column_3d.jl                            | 27.1            | 22.3            | -17.71                    |
| fluid/hydrostatic_water_column_3d.jl with SummationDensity      | 32.8            | 27.1            | -17.38                    |
| fluid/hydrostatic_water_column_edac_2d.jl                       | 16.3            | 13.0            | -20.25                    |
| fluid/accelerated_tank_2d.jl                                    | 15.8            | 13.1            | -17.09                    |
| fluid/dam_break_2d.jl                                           | 32.1            | 23.7            | -26.17                    |
| fluid/dam_break_2d.jl with KernelAbstractions.jl                | 25.3            | 18.4            | -27.27                    |
| fluid/dam_break_3d.jl                                           | 21.1            | 17.2            | -18.48                    |
| fluid/falling_water_column_2d.jl                                | 13.5            | 11.0            | -18.52                    |
| fluid/periodic_channel_2d.jl                                    | 21.4            | 18.5            | -13.55                    |
| fluid/pipe_flow_2d.jl                                           | 53.6            | 52.7            | -1.68                     |
| fluid/dam_break_2d_surface_tension.jl                           | 83.9            | 71.3            | -15.02                    |
| fluid/sphere_surface_tension_2d.jl                              | 10.6            | 7.6             | -28.30                    |
| fluid/sphere_surface_tension_3d.jl                              | 49.6            | 43.4            | -12.50                    |
| fluid/falling_water_spheres_2d.jl                               | 75.9            | 61.6            | -18.84                    |
| fluid/falling_water_spheres_3d.jl                               | 113.3           | 92.7            | -18.19                    |
| fluid/sphere_surface_tension_wall_2d.jl                         | 152             | 132.1           | -13.09                    |
| fluid/moving_wall_2d.jl                                         | 15.4            | 12.5            | -18.83                    |
| dam_break_2d.jl with corrections                                | 340             | 244             | -28.24                    |
| continuity_reinit                                               | 16.1            | 13.2            | -18.01                    |
| gradient_continuity_correction                                  | 31.6            | 20.4            | -35.44                    |
| gradient_summation_correction                                   | 32.9            | 22              | -33.13                    |
| no_correction                                                   | 17.8            | 13.8            | -22.47                    |
| shepard_kernel_correction                                       | 24              | 18.7            | -22.08                    |
| blended_gradient_continuity_correction                          | 30.4            | 20.1            | -33.88                    |
| mixed_kernel_gradient_summation_correction                      | 42.7            | 29.6            | -30.68                    |
| akinci_free_surf_correction                                     | 17.9            | 14.6            | -18.44                    |
| kernel_correction_summation_correction                          | 29.4            | 21              | -28.57                    |
| mixed_kernel_gradient_continuity_correction                     | 38.4            | 28.9            | -24.74                    |
| kernel_correction_continuity_correction                         | 26.4            | 19.3            | -26.89                    |
| blended_gradient_summation_correction                           | 31.6            | 21.7            | -31.33                    |
| Solid                                                           | 21.2            | 12.7            | -40.09                    |
| solid/oscillating_beam_2d.jl                                    | 21.2            | 12.7            | -40.09                    |
| FSI                                                             | 431.6           | 317.4           | -26.48                    |
| fsi/falling_water_column_2d.jl                                  | 28.5            | 19.4            | -31.93                    |
| fsi/dam_break_plate_2d.jl                                       | 59.8            | 47.9            | -19.90                    |
| fsi/dam_break_gate_2d.jl                                        | 238.2           | 164.3           | -31.01                    |
| fsi/falling_spheres_2d.jl                                       | 104.9           | 85.6            | -18.40                    |
| N-Body                                                          | 27.5            | 26.7            | -2.91                     |
| n_body/n_body_solar_system.jl                                   | 5.8             | 4.6             | -20.69                    |
| n_body/n_body_benchmark_trixi.jl                                | 13.9            | 15.0            | 7.91                      |
| n_body/n_body_benchmark_reference.jl                            | 3.9             | 3.3             | -15.38                    |
| n_body/n_body_benchmark_reference_faster.jl                     | 3.8             | 3.7             | -2.63                     |
| Postprocessing                                                  | 46.1            | 35.9            | -22.13                    |
| postprocessing/interpolation_plane.jl                           | 29.3            | 23.4            | -20.14                    |
| postprocessing/interpolation_point_line.jl                      | 2.6             | 2.1             | -19.23                    |
| postprocessing/postprocessing.jl                                | 14.0            | 10.2            | -27.14                    |
| DEM                                                             | 10.7            | 8.9             | -16.82                    |
| dem/rectangular_tank_2d.jl                                      | 10.6            | 8.9             | -16.04                    |
| Validation                                                      | 479.8           | 354.4           | -26.13                    |
| general                                                         | 57.6            | 44.1            | -23.44                    |
| oscillating_beam_2d                                             | 106.6           | 63.1            | -40.80                    |
| dam_break_2d                                                    | 315.4           | 247             | -21.69                    |

**Comment by efaulhaber** [comment]
Do you know where these regressions come from exactly?

**Comment by svchb** [comment]
I did not look into this any further than the CI run times. 1.11 will probably be released in August.

**Comment by svchb** [comment]
RC2:
| Test Category                                                    | Passed | Failed | Total | Time    |
|------------------------------------------------------------------|--------|--------|-------|---------|
| All Tests                                                        | 149    | 2      | 151   | 39m51.6s|
| Examples                                                         | 128    |        | 128   | 32m38.4s|
| Fluid                                                            | 101    |        | 101   | 24m10.6s|
| fluid/oscillating_drop_2d.jl                                     | 4      |        | 4     | 44.3s   |
| fluid/hydrostatic_water_column_2d.jl                             | 3      |        | 3     | 18.9s   |
| fluid/hydrostatic_water_column_2d.jl with source term damping    | 3      |        | 3     | 14.4s   |
| fluid/hydrostatic_water_column_2d.jl with SummationDensity       | 3      |        | 3     | 17.4s   |
| fluid/hydrostatic_water_column_3d.jl                             | 3      |        | 3     | 25.4s   |
| fluid/hydrostatic_water_column_3d.jl with SummationDensity       | 3      |        | 3     | 28.8s   |
| fluid/hydrostatic_water_column_edac_2d.jl                        | 3      |        | 3     | 15.1s   |
| fluid/accelerated_tank_2d.jl                                     | 3      |        | 3     | 15.1s   |
| fluid/dam_break_2d.jl                                            | 3      |        | 3     | 30.0s   |
| fluid/dam_break_oil_film_2d.jl                                   | 3      |        | 3     | 4m56.2s |
| fluid/dam_break_2d.jl with KernelAbstractions.jl                 | 3      |        | 3     | 25.0s   |
| fluid/dam_break_3d.jl                                            | 3      |        | 3     | 19.5s   |
| fluid/falling_water_column_2d.jl                                 | 3      |        | 3     | 12.1s   |
| fluid/periodic_channel_2d.jl                                     | 3      |        | 3     | 21.1s   |
| fluid/pipe_flow_2d.jl                                            | 3      |        | 3     | 54.5s   |
| fluid/dam_break_2d_surface_tension.jl                            | 3      |        | 3     | 1m19.0s |
| fluid/sphere_surface_tension_2d.jl                               | 3      |        | 3     | 9.3s    |
| fluid/sphere_surface_tension_3d.jl                               | 3      |        | 3     | 45.7s   |
| fluid/falling_water_spheres_2d.jl                                | 3      |        | 3     | 1m16.1s |
| fluid/falling_water_spheres_3d.jl                                | 3      |        | 3     | 2m04.7s |
| fluid/sphere_surface_tension_wall_2d.jl                          | 1      |        | 1     | 2m25.1s |
| fluid/moving_wall_2d.jl                                          | 3      |        | 3     | 15.7s   |
| dam_break_2d.jl with corrections                                 | 36     |        | 36    | 5m16.0s |
| continuity_reinit                                                | 3      |        | 3     | 15.5s   |
| gradient_continuity_correction                                   | 3      |        | 3     | 27.8s   |
| gradient_summation_correction                                    | 3      |        | 3     | 29.8s   |
| no_correction                                                    | 3      |        | 3     | 15.9s   |
| shepard_kernel_correction                                        | 3      |        | 3     | 22.6s   |
| blended_gradient_continuity_correction                           | 3      |        | 3     | 27.8s   |
| mixed_kernel_gradient_summation_correction                       | 3      |        | 3     | 41.6s   |
| akinci_free_surf_correction                                      | 3      |        | 3     | 16.3s   |
| kernel_correction_summation_correction                           | 3      |        | 3     | 25.6s   |
| mixed_kernel_gradient_continuity_correction                      | 3      |        | 3     | 39.8s   |
| kernel_correction_continuity_correction                          | 3      |        | 3     | 24.1s   |
| blended_gradient_summation_correction                            | 3      |        | 3     | 28.3s   |
| Solid                                                            | 3      |        | 3     | 19.5s   |
| solid/oscillating_beam_2d.jl                                     | 3      |        | 3     | 19.5s   |
| FSI                                                              | 12     |        | 12    | 6m42.0s |
| fsi/falling_water_column_2d.jl                                   | 3      |        | 3     | 25.4s   |
| fsi/dam_break_plate_2d.jl                                        | 3      |        | 3     | 56.1s   |
| fsi/dam_break_gate_2d.jl                                         | 3      |        | 3     | 3m40.0s |
| fsi/falling_spheres_2d.jl                                        | 3      |        | 3     | 1m40.3s |
| N-Body                                                           | 6      |        | 6     | 27.7s   |
| n_body/n_body_solar_system.jl                                    | 3      |        | 3     | 6.0s    |
| n_body/n_body_benchmark_trixi.jl                                 | 1      |        | 1     | 13.8s   |
| n_body/n_body_benchmark_reference.jl                             | 1      |        | 1     | 3.9s    |
| n_body/n_body_benchmark_reference_faster.jl                      | 1      |        | 1     | 3.8s    |
| Postprocessing                                                   | 6      |        | 6     | 58.6s   |
| postprocessing/interpolation_plane.jl                            | 2      |        | 2     | 41.9s   |
| postprocessing/interpolation_point_line.jl                       | 2      |        | 2     | 2.6s    |
| postprocessing/postprocessing.jl                                 | 2      |        | 2     | 14.0s   |
| DEM                                                              | 3      |        | 3     | 10.0s   |
| dem/rectangular_tank_2d.jl                                       | 3      |        | 3     | 9.9s    |
| Validation                                                       | 18     | 2      | 20    | 7m03.1s |
| general                                                          | 4      |        | 4     | 41.8s   |
| oscillating_beam_2d                                              | 7      |        | 7     | 1m25.9s |

**Comment by svchb** [comment]
Performance regression caused by this https://github.com/JuliaLang/julia/issues/55009

will probably land in 1.12!

**Comment by efaulhaber** [comment]
In the issue they said it's probably going to get backported to 1.11.

**Comment by svchb** [comment]
The last times were 1.9 39:52/40:05 1.10 38:05 1.11 46:11/46:52/47:09 at the time of 1.11 release

**Pull request closed without merging**
